name: CI (NOSJ deserializer + partial collision)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Normalize line endings (LF)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if ls tests/*.py >/dev/null 2>&1; then pip install pytest; fi

      - name: Ensure main.py is executable (if present)
        if: hashFiles('main.py') != ''
        run: chmod +x main.py

      - name: Run NOSJ quick smoke (optional)
        if: hashFiles('spec-testcases/valid/0001.input') != ''
        run: |
          set -e
          ./main.py spec-testcases/valid/0001.input > got.out 2> got.err || true
          diff -u spec-testcases/valid/0001.output got.out || true

      - name: Run auto-runner (if present)
        if: hashFiles('auto-runner.py') != ''
        run: python auto-runner.py

      - name: Run local harness (if present)
        if: hashFiles('run_suite.py') != ''
        run: python run_suite.py

      - name: Run pytest (if present)
        if: hashFiles('tests/**/*.py') != ''
        run: pytest -q

      # ── Partial SHA256 collision ───────────────────────────────────────────
      - name: Partial collision — generate inputs & digests (4 threads)
        working-directory: partial-collision
        run: make THREADS=4 run

      - name: Partial collision — verify (email prefix + last 4 bytes)
        working-directory: partial-collision
        run: make THREADS=4 verify

      - name: Upload partial-collision artifacts
        uses: actions/upload-artifact@v4
        with:
          name: partial-collision-output
          path: |
            partial-collision/1-input.txt
            partial-collision/1-sha256-digest.txt
            partial-collision/2-input.txt
            partial-collision/2-sha256-digest.txt
            partial-collision/out.txt
