name: CI (NOSJ deserializer)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Keep LF line endings so byte compares match the grader.
      - name: Normalize line endings (LF)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optional if you keep unit tests
          if ls tests/*.py >/dev/null 2>&1; then pip install pytest; fi

      - name: Ensure main.py is executable
        run: chmod +x main.py

      - name: Show repo tree (quick sanity)
        run: |
          pwd
          ls -la
          echo
          ls -la Deserializer || true
          echo
          head -n 3 main.py

      - name: Show Makefile run command
        run: |
          make -n run FILE=spec-testcases/valid/0001.input || true

      - name: Run one valid case (capture & compare)
        run: |
          set -e
          ./main.py spec-testcases/valid/0001.input > got.out 2> got.err || true
          echo "=== exit: $?"
          echo "--- stdout (got.out) ---"; cat -A got.out
          echo "--- stderr (got.err) ---"; cat -A got.err
          echo "--- expected ---"; cat -A spec-testcases/valid/0001.output
          diff -u spec-testcases/valid/0001.output got.out || true

      - name: Run auto-runner (spec-testcases)
        run: |
          python auto-runner.py

      - name: Run local harness (run_suite.py)
        if: hashFiles('run_suite.py') != ''
        run: |
          python run_suite.py

      - name: Run pytest
        if: hashFiles('tests/**/*.py') != ''
        run: |
          pytest -q
